### PR TITLE
Added postcss-loader webpackrule.

### PR DESCRIPTION
**Pull request by sabmark**
Added postcss-loader webpackrule. No other options needed as customization can be done in` postcss.config.js`

### CODE REVIEW

**Comment by Nothing-Works** [comment]
@sabmark hi, thank you for your pr, just one thing, can I know the scenario why you want to add `postcss`? as `generateRules()` is really for `vuetify` internally compiling. So I think it does not need `postcss-loader`. or do you want to write your own css in `postcss`? please let me know if I am missing something.

**Comment by sabmark** [comment]
@Nothing-Works we have this existing project where the vuejs/vuetify app is just a portion of the page. So the existing page uses bootstrap, the problem now is vuetify has the same grid classes `.row`, .`col-`, button classes `.btn .btn-sm` and `submit` that will interfere with the existing outside of the app classes. We solve it by using [poscss-prefix-selector](https://www.npmjs.com/package/postcss-prefix-selector) with the tranformation below:

`postcss.config.js`
```
module.exports = ({ file, options, env }) => ({
    parser: file.extname === '.sss' ? 'sugarss' : false,
    plugins: {
        precss: {},
        'postcss-prefix-selector': {
            prefix: '.vue-app-root-class',
            transform: (prefix, selector) => {
                const isColumn = selector.includes('.col-');
                const isBtn = selector.includes('button');
                const isSubmit = selector.includes('submit');

                if (selector === '.row' || isColumn || isBtn || isSubmit) {
                    return `${prefix} ${selector}`;
                } else {
                    return selector;
                }
            },
        },
    },
});
```
then
`<v-app class="vue-app-root-class">`

more info here: https://stackoverflow.com/questions/51717264/styling-vuetify-selectors/51728504#51728504

**Comment by Nothing-Works** [comment]
@sabmark Hi very sorry for the delayed response, I just want to make sure that I understand this correctly. So basically what you were doing is that:

1. change `.scss or .sass` to`postcss` first.
2. add `postcss-prefix-selector`.
3. compile to normal `css`.

Did I understand it correctly? And have you tested your PR? is it working for you fine?
We can enable this but I think this should not be by default, we may need to pass the option to enable it.

**Comment by sabmark** [comment]
@Nothing-Works 

1. Applying postcss processes after css-loader.
2. Add [whatever plugin](https://www.postcss.parts/) you want for postcss process (for me I will be using `postcss-prefix-selector` for some purposes) within `postcss.config.js` file.
3. Yes, I believe so.

Yes, It is working for me just fine. Sure thing, we can make this one optional (But I think it's already optional, if you don't add anything on `postcss.config.js` file or no file at all, then postcss won't have any effect.).

**Comment by Nothing-Works** [comment]
@sabmark yes, I agree the only thing is that the extra dependency for someone doesn't need postcss processing.

**Comment by Nothing-Works** [comment]
@sabmark I had some problems with making it by default, so you may need to do this way. `mix.js('resources/js/app.js', 'public/js').vuetify('', { postcss: true })`

**Comment by sabmark** [comment]
@Nothing-Works cool, thanks!

**Pull request merged**
